In [2]:
import numpy as np
import pandas as pd

from pandas import DataFrame

In [3]:
df = pd.read_csv('IAfloodsNOAA.csv')

In [4]:
floodData = DataFrame(df)
print(floodData)

     EVENT_ID     CZ_NAME_STR BEGIN_LOCATION BEGIN_DATE  BEGIN_TIME  \
0     5540507     POLK (ZONE)                  2/9/1996         600
1     5540510   MARION (ZONE)                  2/9/1996         600
2     5540511  MAHASKA (ZONE)                  2/9/1996         600
3     5540506   DALLAS (ZONE)                  2/9/1996         600
4     5540508   JASPER (ZONE)                  2/9/1996         600
..        ...             ...            ...        ...         ...
495   5653150    STORY (ZONE)                 6/14/1998         900
496   5653143  GUTHRIE (ZONE)                 6/14/1998         900
497   5653151     TAMA (ZONE)                 6/14/1998         900
498   5653135   HARDIN (ZONE)                 6/14/1998         900
499   5653138  CARROLL (ZONE)                 6/14/1998         900

    EVENT_TYPE MAGNITUDE TOR_F_SCALE  DEATHS_DIRECT  INJURIES_DIRECT  ...  \
0        Flood                                    0                0  ...
1        Flood                                    0                0  ...
2        Flood                                    0                0  ...
3        Flood                                    0                0  ...
4        Flood                                    0                0  ...
..         ...       ...         ...            ...              ...  ...
495      Flood                                    0                0  ...
496      Flood                                    0                0  ...
497      Flood                                    0                0  ...
498      Flood                                    0                0  ...
499      Flood                                    0                0  ...

     Unnamed: 42  Unnamed: 43 Unnamed: 44 Unnamed: 45 Unnamed: 46  \
0            NaN          NaN         NaN         NaN         NaN
1            NaN          NaN         NaN         NaN         NaN
2            NaN          NaN         NaN         NaN         NaN
3            NaN          NaN         NaN         NaN         NaN
4            NaN          NaN         NaN         NaN         NaN
..           ...          ...         ...         ...         ...
495          NaN          NaN         NaN         NaN         NaN
496          NaN          NaN         NaN         NaN         NaN
497          NaN          NaN         NaN         NaN         NaN
498          NaN          NaN         NaN         NaN         NaN
499          NaN          NaN         NaN         NaN         NaN

     Unnamed: 47 Unnamed: 48  Unnamed: 49 Unnamed: 50  Unnamed: 51
0            NaN         NaN          NaN         NaN          NaN
1            NaN         NaN          NaN         NaN          NaN
2            NaN         NaN          NaN         NaN          NaN
3            NaN         NaN          NaN         NaN          NaN
4            NaN         NaN          NaN         NaN          NaN
..           ...         ...          ...         ...          ...
495          NaN         NaN          NaN         NaN          NaN
496          NaN         NaN          NaN         NaN          NaN
497          NaN         NaN          NaN         NaN          NaN
498          NaN         NaN          NaN         NaN          NaN
499          NaN         NaN          NaN         NaN          NaN

[500 rows x 52 columns]

In [38]:
floodData.dropna(thresh=50, axis=1, inplace=True)
floodData.replace(' ', np.nan, inplace=True)
floodData.dropna(axis=1, how='all', inplace=True)
floods = floodData.drop(floodData[floodData['EVENT_TYPE'] != 'Flood'].index)
flashFloods = floodData.drop(floodData[floodData['EVENT_TYPE'] != 'Flash Flood'].index)

In [50]:
flashFloods.loc[:,["EVENT_ID","EVENT_TYPE", "CZ_NAME_STR","INJURIES_DIRECT", "DEATHS_DIRECT", "DAMAGE_PROPERTY_NUM", "DAMAGE_CROPS_NUM","INJURIES_INDIRECT", "DEATHS_INDIRECT",]]

,EVENT_ID,EVENT_TYPE,CZ_NAME_STR,INJURIES_DIRECT,DEATHS_DIRECT,DAMAGE_PROPERTY_NUM,DAMAGE_CROPS_NUM,INJURIES_INDIRECT,DEATHS_INDIRECT
14,5569867,Flash Flood,VAN BUREN CO.,0,0,0,0,0,0
15,5545086,Flash Flood,MAHASKA CO.,0,0,500000,0,0,0
46,5569868,Flash Flood,WASHINGTON CO.,0,0,0,0,0,0
91,5544487,Flash Flood,POLK CO.,0,0,300000,50000,0,0
92,5544488,Flash Flood,ADAIR CO.,0,0,75000,50000,0,0
93,5544489,Flash Flood,CASS CO.,0,0,75000,50000,0,0
118,5553459,Flash Flood,SAC CO.,0,0,200000,25000,0,0
119,5553460,Flash Flood,CALHOUN CO.,0,0,150000,20000,0,0
123,5553467,Flash Flood,BOONE CO.,0,0,400000,100000,0,0
124,5553468,Flash Flood,HAMILTON CO.,0,0,200000,100000,0,0
125,5553469,Flash Flood,STORY CO.,0,0,1500000,100000,0,0
126,5553470,Flash Flood,HARDIN CO.,0,0,200000,100000,0,0
158,5553659,Flash Flood,SAC CO.,0,0,50000,10000,0,0
173,5553666,Flash Flood,CRAWFORD CO.,0,0,11000000,150000,0,0
175,5553665,Flash Flood,CARROLL CO.,0,0,250000,75000,0,0
177,5563941,Flash Flood,MONONA CO.,0,0,0,0,0,0
178,5563942,Flash Flood,HARRISON CO.,0,0,0,0,0,0
179,5563943,Flash Flood,SHELBY CO.,0,0,0,0,0,0
180,5563944,Flash Flood,HARRISON CO.,0,0,0,0,0,0
181,5563947,Flash Flood,PAGE CO.,0,0,0,0,0,0
183,5556819,Flash Flood,WOODBURY CO.,0,0,1000000,0,0,0
185,5561788,Flash Flood,CRAWFORD CO.,0,0,300000,200000,0,0
186,5561794,Flash Flood,CARROLL CO.,0,0,300000,200000,0,0
245,5586136,Flash Flood,POLK CO.,0,1,30000,0,0,0
246,5586137,Flash Flood,POLK CO.,0,0,100000,0,0,0
247,5589259,Flash Flood,JACKSON CO.,0,0,0,0,0,0
248,5589273,Flash Flood,LEE CO.,0,0,0,0,0,0
249,5589261,Flash Flood,JOHNSON CO.,0,0,0,0,0,0
250,5589263,Flash Flood,CLINTON CO.,0,0,0,0,0,0
251,5589264,Flash Flood,MUSCATINE CO.,0,0,0,0,0,0
252,5589254,Flash Flood,BUCHANAN CO.,0,0,0,0,0,0
253,5589255,Flash Flood,DELAWARE CO.,0,0,0,0,0,0
254,5589267,Flash Flood,WASHINGTON CO.,0,0,0,0,0,0
255,5589269,Flash Flood,JEFFERSON CO.,0,0,0,0,0,0
256,5589270,Flash Flood,HENRY CO.,0,0,0,0,0,0
257,5589268,Flash Flood,LOUISA CO.,0,0,0,0,0,0
258,5589271,Flash Flood,DES MOINES CO.,0,0,0,0,0,0
259,5589272,Flash Flood,VAN BUREN CO.,0,0,0,0,0,0
260,5589265,Flash Flood,SCOTT CO.,0,0,0,0,0,0
261,5589266,Flash Flood,KEOKUK CO.,0,0,0,0,0,0
262,5589256,Flash Flood,DUBUQUE CO.,0,0,0,0,0,0
263,5589257,Flash Flood,LINN CO.,0,0,0,0,0,0
264,5589258,Flash Flood,JONES CO.,0,0,0,0,0,0
265,5589262,Flash Flood,CEDAR CO.,0,0,0,0,0,0
266,5589260,Flash Flood,IOWA CO.,0,0,0,0,0,0
386,5598878,Flash Flood,BUTLER CO.,0,0,200000,100000,0,0
387,5598879,Flash Flood,FRANKLIN CO.,0,0,200000,100000,0,0
388,5598880,Flash Flood,HANCOCK CO.,0,0,100000,50000,0,0
389,5598881,Flash Flood,WRIGHT CO.,0,0,100000,50000,0,0
390,5603028,Flash Flood,PALO ALTO CO.,0,0,100000,5000,0,0
397,5603125,Flash Flood,POLK CO.,0,0,200000,20000,0,0
398,5603146,Flash Flood,PALO ALTO CO.,0,0,150000,20000,0,0
399,5609905,Flash Flood,MUSCATINE CO.,0,0,0,0,0,0
400,5617997,Flash Flood,POTTAWATTAMIE CO.,0,0,0,0,0,0
401,5617998,Flash Flood,MILLS CO.,0,0,0,0,0,0
483,5654076,Flash Flood,CASS CO.,0,0,2000000,1200000,0,0

In [54]:
floods.loc[:,["EVENT_ID","EVENT_TYPE", "CZ_NAME_STR","INJURIES_DIRECT", "DEATHS_DIRECT", "DAMAGE_PROPERTY_NUM", "DAMAGE_CROPS_NUM","INJURIES_INDIRECT", "DEATHS_INDIRECT",]]

,EVENT_ID,EVENT_TYPE,CZ_NAME_STR,INJURIES_DIRECT,DEATHS_DIRECT,DAMAGE_PROPERTY_NUM,DAMAGE_CROPS_NUM,INJURIES_INDIRECT,DEATHS_INDIRECT
0,5540507,Flood,POLK (ZONE),0,0,0,0,0,0
1,5540510,Flood,MARION (ZONE),0,0,0,0,0,0
2,5540511,Flood,MAHASKA (ZONE),0,0,50000,0,0,0
3,5540506,Flood,DALLAS (ZONE),0,0,0,0,0,0
4,5540508,Flood,JASPER (ZONE),0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
495,5653150,Flood,STORY (ZONE),0,0,100000,20000,0,0
496,5653143,Flood,GUTHRIE (ZONE),0,0,1000000,100000,0,0
497,5653151,Flood,TAMA (ZONE),0,0,100000,20000,0,0
498,5653135,Flood,HARDIN (ZONE),0,0,100000,20000,0,0
499,5653138,Flood,CARROLL (ZONE),0,0,100000,20000,0,0